
#line 3 "scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 130
#define YY_END_OF_BUFFER 131
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[533] =
    {   0,
        0,    0,  131,  129,  127,  128,  127,  123,  129,    5,
      122,  126,  129,  114,  115,  120,  119,  111,  118,  129,
      121,   84,   84,  112,  108,  106,  113,  107,  105,   81,
       81,   81,   81,   81,  116,  117,  124,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,  109,  125,  110,    0,
        5,  102,    0,   89,    0,    0,    0,    0,   94,   97,
        0,    0,   92,   95,   90,   96,   91,   87,   64,   63,
       93,   88,   83,    0,   84,    0,   84,  104,   99,  101,
      100,  103,   81,   81,   81,   81,   81,   48,   48,   81,

       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       72,   81,   81,   81,   81,   81,   81,   81,   76,   48,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   98,    0,
        0,   85,    0,   87,   87,    0,   88,   83,    0,   86,
       82,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   49,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   74,   81,   81,   81,   65,   81,   81,   81,   44,

       81,   43,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,    0,    0,    0,   87,    0,   87,    0,   88,   86,
       82,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   14,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   73,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   27,   81,
       81,   81,   81,   23,   81,   39,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   32,

       61,   81,   81,   81,   66,   81,   81,   81,    4,    0,
        0,   87,   81,   81,   81,   81,   81,   81,   81,   81,
       50,   81,   81,   81,   81,   81,   70,   81,   81,   81,
       81,   81,   81,   81,   81,   36,   81,   22,   81,   81,
       81,   59,   81,   81,   57,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   56,   81,   81,   81,   81,
       81,   81,   55,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   77,   81,   40,    0,   51,   81,   81,   81,
       81,   81,   81,   21,   81,   81,   81,   81,   81,   29,
       81,   81,   81,   81,   81,   60,   12,   81,   18,   81,

        8,   81,   81,   81,   81,   69,   81,   67,   81,   81,
       81,   26,   17,   81,   81,   81,   75,   54,   81,   81,
       81,   81,   81,   33,   42,   81,   81,    0,   81,   81,
       81,   81,   81,   81,   81,   20,   41,   81,   81,   81,
       81,   81,   11,   81,   81,   81,   81,    9,   81,   68,
       81,   13,   81,   16,   81,   78,   81,   45,   81,   81,
       81,   81,   81,   58,    0,   52,   62,   15,   35,   71,
       81,   19,   81,   81,   81,   81,    6,   81,   10,    7,
       79,   81,   81,   47,   34,   81,   81,    0,   81,   81,
       81,   37,   81,   28,   80,   81,   38,   81,    0,   81,

       81,   81,   81,   81,   46,    0,   31,   81,   25,   30,
       81,    2,    0,   24,   53,    0,    0,    0,    1,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    3,
        3,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   33,   36,   37,   33,   38,   39,   33,
       33,   40,   33,   41,   42,   33,   43,   44,   33,   33,
       45,   46,   47,   48,   49,    1,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   33,   59,   60,   61,   62,
       63,   64,   33,   65,   66,   67,   68,   69,   70,   71,
       72,   33,   73,   74,   75,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[76] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1,    1,    4,    3,
        3,    3,    3,    3,    3,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[537] =
    {   0,
        0,    0,  688,  689,   74,  689,  689,  663,   71,   76,
      662,  676,  638,  689,  689,  659,   65,  689,   64,   63,
       72,   67,   83,  689,  689,   68,  658,   69,  689,   56,
        0,   64,   67,   64,  689,  689,  689,   78,   51,   63,
       76,  621,   52,   39,   69,   84,   99,   87,   54,   91,
       90,  108,  113,   90,  617,  107,  689,  605,  689,  166,
      140,  689,  155,  689,  675,  165,  619,  611,  689,  689,
      164,  173,  689,  689,  689,  689,  689,  158,  689,  689,
      689,  160,  186,  168,  156,    0,  202,  689,  689,  689,
      689,  689,    0,  143,  164,  634,  607,  634,  146,  631,

      604,  615,  168,  602,  603,  613,  602,  181,  607,  597,
        0,  601,  596,  134,  593,  595,  596,  600,    0,  169,
      591,  604,  171,  590,  592,  195,  592,  599,  584,  585,
      591,  597,  197,  585,  192,  594,  595,  582,  591,  201,
      576,  587,  573,  200,  581,  580,  572,  578,  689,  573,
      584,  689,  253,  689,  255,  262,  689,  243,  239,  264,
      252,  594,  593,  568,  567,  566,  565,  600,  576,  583,
      556,  555,    0,  564,  558,  559,  556,  555,  552,  566,
      548,  554,  546,  540,  544,  560,  559,  554,  557,  540,
      539,    0,  553,  550,  534,    0,  534,  550,  532,    0,

      542,    0,  543,  542,  545,  545,  539,  542,  522,  530,
      536,  520,  519,  519,  531,  520,  516,  517,  525,  230,
      212,  522,  520,  525,  519,  526,  513,  521,  513,  513,
      504,  516,  513,  241,  285,  307,  689,  271,  309,  689,
      265,  538,  527,  513,  500,  511,  498,  533,  509,  519,
      492,  491,  495,  503,  497,  489,    0,  495,  493,  483,
      500,  491,  242,  490,  495,  485,    0,  485,  477,  486,
      492,  487,  473,  475,  478,  483,  482,  469,    0,  476,
      466,  467,  471,  480,  471,    0,  476,  462,  468,  472,
      470,  465,  468,  461,  458,  231,  452,  460,  464,  265,

        0,  462,  448,  449,    0,  459,  458,  457,  689,  449,
      278,  319,  478,  472,  453,  447,  451,  445,  469,  445,
        0,  443,  446,  447,  439,  443,    0,  431,  431,  432,
      431,  427,  439,  433,  431,    0,  424,    0,  427,  433,
      420,    0,  419,  433,    0,  415,  424,  426,  419,  411,
      425,  409,  413,  413,  405,    0,  409,  418,  416,  405,
      414,  400,    0,  414,  411,  410,  262,  413,  404,  408,
      406,  405,    0,  393,    0,  407,    0,  425,  401,  400,
      422,  398,  384,    0,  396,  384,  394,  381,  378,    0,
      387,  394,  389,  390,  376,    0,    0,  382,    0,  388,

        0,  373,  384,  382,  381,    0,  376,    0,  379,  372,
      369,    0,    0,  362,  367,  364,    0,    0,  372,  369,
      363,  366,  369,    0,    0,  355,  355,  418,  379,  353,
      352,  386,  362,  342,  348,    0,    0,  358,  357,  341,
      349,  355,    0,  349,  337,  345,  350,    0,  343,    0,
      339,    0,  347,  334,  332,    0,  330,    0,  343,  344,
      328,  334,  325,    0,  250,    0,    0,    0,    0,    0,
      342,    0,  322,  340,  331,  328,    0,  315,    0,    0,
        0,  309,  322,    0,    0,  320,  306,  309,  301,  317,
      299,    0,  312,    0,    0,  295,    0,  300,  297,  306,

      292,  304,  291,  295,    0,  314,    0,  300,    0,    0,
      299,  269,  281,    0,    0,  293,  347,  283,  345,  290,
      293,  289,  268,  265,  250,  199,  185,  160,  157,  206,
      192,  689,  379,  383,  385,  105
    } ;

static yyconst flex_int16_t yy_def[537] =
    {   0,
      532,    1,  532,  532,  532,  532,  532,  532,  533,  532,
      532,  532,  534,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  535,
      535,  535,  535,  535,  532,  532,  532,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  532,  532,  532,  532,
      532,  532,  533,  532,  533,  532,  532,  532,  532,  532,
      534,  534,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  536,  532,  532,  532,  532,
      532,  532,  535,  535,  535,  535,  535,  535,  535,  535,

      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      536,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,

      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,

      535,  535,  535,  535,  535,  535,  535,  535,  532,  532,
      532,  532,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  532,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,

      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  532,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  532,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  532,  535,  535,
      535,  535,  535,  535,  535,  535,  535,  535,  532,  535,

      535,  535,  535,  535,  535,  532,  535,  535,  535,  535,
      535,  532,  532,  535,  535,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,    0,  532,  532,  532,  532
    } ;

static yyconst flex_int16_t yy_nxt[765] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   31,   32,
       31,   31,   31,   31,   33,   31,   31,   31,   34,   31,
       31,   31,   31,   31,   35,    4,   36,   37,   31,   38,
       39,   40,   41,   42,   43,   44,   31,   45,   31,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       31,   31,   57,   58,   59,   60,   64,   66,   74,   76,
       61,   78,   78,   82,   79,   83,   83,   77,   75,   80,
       88,   89,   91,   92,   96,   81,   94,   84,  117,   82,

      105,   87,   87,   85,   98,  100,  118,  161,   85,  114,
       86,  115,  107,   84,  116,  106,   65,   97,  128,   85,
       84,  129,   95,  119,   85,  108,   85,  109,   99,  110,
      120,  101,  102,  121,   85,   67,   84,   86,  111,   68,
      130,   66,   85,  133,  103,  104,  122,  112,  123,  126,
       85,  143,  124,  144,  127,  131,  125,  134,  132,  135,
       64,  136,  141,  146,  137,  138,   66,   60,  139,  147,
      142,  148,   61,  152,  140,  532,   78,   78,  155,  155,
      162,  159,   71,  159,  171,  163,  160,  160,  153,  154,
      156,  157,   85,  531,  154,  189,  157,   85,  190,   67,

       65,  164,   82,   68,   83,   83,  165,  531,  172,   72,
      530,  153,  154,  156,  157,   85,   84,  154,   82,  157,
       87,   87,  158,   85,   67,  166,  529,  158,   68,  175,
      176,  195,   84,  167,  528,  196,  199,  177,   85,   84,
      182,  200,  183,   85,  184,  158,  211,  203,  215,  212,
      221,  465,  226,  158,  216,   84,  204,  160,  160,  235,
      235,   85,  227,  213,  205,  222,  234,  527,  234,   85,
      512,  235,  235,  155,  155,  238,  297,  238,  298,  158,
      239,  239,  160,  160,  158,  236,  237,  295,  241,  239,
      239,  237,  296,  241,  361,  240,  312,  312,  362,  331,

      240,  241,  158,  235,  235,  332,  241,  526,  236,  237,
      158,  241,  488,  420,  237,  512,  154,  366,  240,  241,
      311,  154,  311,  240,  241,  312,  312,  239,  239,  525,
      367,  524,  241,  421,  368,  516,  369,  312,  312,  154,
      157,  523,  522,  521,  154,  157,  519,  520,  519,  518,
      237,  517,  515,  514,  511,  237,  510,  509,  508,  507,
      506,  505,  504,  157,  503,  502,  501,  500,  157,  499,
      498,  513,  497,  237,  496,  495,  494,  493,  237,   63,
       63,   63,   63,   71,  492,   71,   71,   93,   93,  491,
      490,  489,  487,  486,  485,  484,  483,  482,  481,  480,

      479,  478,  477,  476,  475,  474,  473,  467,  472,  471,
      470,  469,  466,  468,  467,  467,  466,  466,  466,  465,
      464,  463,  462,  461,  460,  459,  458,  457,  456,  455,
      454,  453,  452,  451,  450,  449,  448,  447,  446,  445,
      444,  443,  442,  441,  440,  439,  438,  437,  436,  435,
      434,  433,  432,  431,  430,  429,  428,  427,  426,  425,
      424,  423,  422,  419,  418,  417,  416,  415,  414,  413,
      412,  411,  410,  409,  408,  407,  406,  405,  404,  403,
      402,  401,  400,  399,  398,  397,  396,  395,  394,  393,
      392,  391,  390,  389,  388,  387,  386,  385,  384,  377,

      383,  382,  381,  380,  377,  379,  377,  378,  377,  376,
      375,  374,  373,  372,  371,  370,  365,  364,  363,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  345,  344,  343,  342,  341,  321,
      340,  339,  338,  337,  336,  335,  334,  333,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  321,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  310,  309,
      308,  307,  306,  305,  304,  303,  302,  301,  300,  299,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,

      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  233,  232,  231,  230,  229,  228,  225,
      224,  223,  220,  219,  218,  217,  214,  210,  209,  208,
      173,  207,  206,  202,  201,  198,  197,  194,  193,  192,
      191,  188,  187,  186,  185,  181,  180,  179,  178,  174,
      173,  173,  170,  169,  168,  151,  150,  532,  149,  145,
      113,   90,   73,   72,   70,   69,   62,  532,    3,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,

      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532
    } ;

static yyconst flex_int16_t yy_chk[765] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    9,   10,   17,   19,
        5,   20,   20,   22,   21,   22,   22,   19,   17,   21,
       26,   26,   28,   28,   32,   21,   30,   22,   44,   23,

       39,   23,   23,   22,   33,   34,   44,  536,   22,   43,
       22,   43,   40,   23,   43,   39,    9,   32,   49,   23,
       22,   49,   30,   45,   23,   40,   22,   40,   33,   41,
       45,   34,   38,   46,   22,   10,   23,   22,   41,   10,
       50,   61,   23,   51,   38,   38,   46,   41,   47,   48,
       23,   54,   47,   54,   48,   50,   47,   51,   50,   52,
       63,   52,   53,   56,   52,   52,   66,   60,   52,   56,
       53,   56,   60,   71,   52,   72,   78,   78,   82,   82,
       94,   84,   72,   84,   99,   94,   84,   84,   78,   78,
       82,   82,   85,  531,   78,  114,   82,   85,  114,   61,

       63,   95,   83,   61,   83,   83,   95,  530,   99,   71,
      529,   78,   78,   82,   82,   85,   83,   78,   87,   82,
       87,   87,   83,   85,   66,   95,  528,   83,   66,  103,
      103,  120,   87,   95,  527,  120,  123,  103,   87,   83,
      108,  123,  108,   87,  108,   83,  133,  126,  135,  133,
      140,  465,  144,   83,  135,   87,  126,  159,  159,  234,
      234,   87,  144,  133,  126,  140,  153,  526,  153,   87,
      512,  153,  153,  155,  155,  156,  221,  156,  221,  158,
      156,  156,  160,  160,  158,  155,  155,  220,  161,  238,
      238,  155,  220,  161,  296,  160,  311,  311,  296,  263,

      160,  241,  158,  235,  235,  263,  241,  525,  155,  155,
      158,  161,  465,  367,  155,  506,  235,  300,  160,  161,
      236,  235,  236,  160,  241,  236,  236,  239,  239,  524,
      300,  523,  241,  367,  300,  512,  300,  312,  312,  235,
      239,  522,  521,  520,  235,  239,  519,  518,  517,  516,
      312,  513,  511,  508,  504,  312,  503,  502,  501,  500,
      499,  498,  496,  239,  493,  491,  490,  489,  239,  488,
      487,  506,  486,  312,  483,  482,  478,  476,  312,  533,
      533,  533,  533,  534,  475,  534,  534,  535,  535,  474,
      473,  471,  463,  462,  461,  460,  459,  457,  455,  454,

      453,  451,  449,  447,  446,  445,  444,  442,  441,  440,
      439,  438,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  426,  423,  422,  421,  420,  419,  416,  415,  414,
      411,  410,  409,  407,  405,  404,  403,  402,  400,  398,
      395,  394,  393,  392,  391,  389,  388,  387,  386,  385,
      383,  382,  381,  380,  379,  378,  376,  374,  372,  371,
      370,  369,  368,  366,  365,  364,  362,  361,  360,  359,
      358,  357,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  344,  343,  341,  340,  339,  337,  335,  334,
      333,  332,  331,  330,  329,  328,  326,  325,  324,  323,

      322,  320,  319,  318,  317,  316,  315,  314,  313,  310,
      308,  307,  306,  304,  303,  302,  299,  298,  297,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  285,  284,
      283,  282,  281,  280,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  266,  265,  264,  262,  261,
      260,  259,  258,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      219,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  204,  203,  201,  199,  198,

      197,  195,  194,  193,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  151,  150,  148,  147,  146,  145,  143,
      142,  141,  139,  138,  137,  136,  134,  132,  131,  130,
      129,  128,  127,  125,  124,  122,  121,  118,  117,  116,
      115,  113,  112,  110,  109,  107,  106,  105,  104,  102,
      101,  100,   98,   97,   96,   68,   67,   65,   58,   55,
       42,   27,   16,   13,   12,   11,    8,    3,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,

      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532,  532,  532,  532,  532,  532,  532,
      532,  532,  532,  532
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
/*
  OMPi OpenMP Compiler
  == Copyright since 2001 the OMPi Team
  == Department of Computer Science, University of Ioannina

  This file is part of OMPi.

  OMPi is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  OMPi is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with OMPi; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/
#line 32 "scanner.l"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "ompi.h"
#include "ast.h"            /* For the yylval / ast types */
#include "symtab.h"
#include "parser.h"
#include "scanner.h"

#define SCANNER_STR_SIZES 1024  /* All strings declared here are that long */

static int  on_omp_line = 0,    /* Scanning an OpenMP #pragma line */
            on_ompix_line = 0;  /* Scanning an OMPi-extension #pragma line */
int         __has_omp = 0,      /* True if we found at least 1 OpenMP #pragma */
            __has_ompix = 0,
            __has_affinitysched = 0;

void count(), gobbleline(), sharp(), gobblecomment();

#define IdentOrType() \
  ( symtab_get(stab,Symbol(yytext),TYPENAME) != NULL ? TYPENAME : IDENTIFIER )

/* The following variables are used for tracking the original filenames and
 * original line numbers, because our scanner/parser uses preprocessed
 * files. To do this, we parse the sharps produced by the preprocessor,
 * which mark the line number of the original file, in the of the form:
 *   # 1 "test.c"
 */
static char origfile_name[SCANNER_STR_SIZES];  // original file name
static char thisfile_name[SCANNER_STR_SIZES];  // the scanned file name
static int  thisfile_line = 1, // Current line in our file (preprocessed)
            marker_line = 0,   // The line where the last marker was found
            origfile_line = 0; // Original file line the marker was refering to
static int  thisfile_column = 0;  // Column in the currently scanned line
static int  start_token = 0;   // For starting with a particular token

#line 857 "scanner.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 72 "scanner.l"



     /* Trick to get an initial token (from the bison manual);
      * This is placed in the top of the produced yylex() function.
      */
     if (start_token)
     {
       int t = start_token;
       start_token = 0;         /* Don't do it again */
       return t;
     }



#line 1055 "scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 533 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 689 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 87 "scanner.l"
{
    count();
    on_ompix_line = __has_ompix = 1;
    return (PRAGMA_OMPIX);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 93 "scanner.l"
{
    count();
    on_omp_line = __has_omp = 1;
    return (PRAGMA_OMP);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 98 "scanner.l"
{
    count();
    on_omp_line = __has_omp = 1;
    return (PRAGMA_OMP_THREADPRIVATE);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 103 "scanner.l"
{
    sharp();
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 106 "scanner.l"
{
    sharp();
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 109 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_PARALLEL);
    else
    return IdentOrType();
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 116 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_SECTIONS);
    else
    return IdentOrType();
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 123 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_NOWAIT);
    else
    return IdentOrType();
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 130 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_ORDERED);
    else
    return IdentOrType();
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 137 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_SCHEDULE);
    else
    return IdentOrType();
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 144 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_DYNAMIC);
    else
    return IdentOrType();
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 151 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_GUIDED);
    else
    return IdentOrType();
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 158 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_RUNTIME);
    else
    return IdentOrType();
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 166 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_AUTO);
    //else
    //return(AUTO);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 174 "scanner.l"
{ 
    count();
    if (on_omp_line)
    {
        __has_affinitysched = 1;
        return(OMP_AFFINITY);
    }
    else
    return IdentOrType();
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 184 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_SECTION);
    else
    return IdentOrType();
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 191 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_SINGLE);
    else
    return IdentOrType();
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 198 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_MASTER);
    else
    return IdentOrType();
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 205 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_CRITICAL);
    else
    return IdentOrType();
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 212 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_BARRIER);
    else
    return IdentOrType();
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 219 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_ATOMIC);
    else
    return IdentOrType();
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 226 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_FLUSH);
    else
    return IdentOrType();
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 234 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_PRIVATE);
    else
    return IdentOrType();
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 241 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_FIRSTPRIVATE);
    else
    return IdentOrType();
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 248 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_LASTPRIVATE);
    else
    return IdentOrType();
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 255 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_SHARED);
    else
    return IdentOrType();
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 262 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_NONE);
    else
    return IdentOrType();
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 269 "scanner.l"
{
    count();
    if (on_omp_line || on_ompix_line)
    return(OMP_REDUCTION);
    else return IdentOrType();
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 275 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_COPYIN);
    else
    return IdentOrType();
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 282 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_NUMTHREADS);
    else
    return IdentOrType();
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 289 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_COPYPRIVATE);
    else
    return IdentOrType();
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 298 "scanner.l"
{
    count();
    if (on_omp_line || on_ompix_line)
    return(OMP_TASK);
    else
    return IdentOrType();
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 305 "scanner.l"
{
    count();
    if (on_omp_line || on_ompix_line)
    return(OMP_UNTIED);
    else
    return IdentOrType();
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 312 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_TASKWAIT);
    else
    return IdentOrType();
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 319 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_COLLAPSE);
    else
    return IdentOrType();
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 327 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_FINAL);
    else
    return IdentOrType();
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 334 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_MERGEABLE);
    else
    return IdentOrType();
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 341 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_TASKYIELD);
    else
    return IdentOrType();
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 348 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_READ);
    else
    return IdentOrType();
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 355 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_WRITE);
    else
    return IdentOrType();
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 362 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_CAPTURE);
    else
    return IdentOrType();
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 369 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_UPDATE);
    else
    return IdentOrType();
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 376 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_MIN);
    else
    return IdentOrType();
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 383 "scanner.l"
{
    count();
    if (on_omp_line)
    return(OMP_MAX);
    else
    return IdentOrType();
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 392 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_TASKDEF);
    else
    return IdentOrType();
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 399 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_UPONRETURN);
    else
    return IdentOrType();
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 406 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_TASKSYNC);
    else
    return IdentOrType();
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 413 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_IN);
    else
    return IdentOrType();
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 420 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_OUT);
    else
    return IdentOrType();
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 427 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_INOUT);
    else
    return IdentOrType();
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 434 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_ATNODE);
    else
    return IdentOrType();
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 441 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_ATWORKER);
    else
    return IdentOrType();
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 448 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_TASKSCHEDULE);
    else
    return IdentOrType();
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 455 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_STRIDE);
    else
    return IdentOrType();
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 462 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_START);
    else
    return IdentOrType();
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 469 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_SCOPE);
    else
    return IdentOrType();
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 476 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_NODES);
    else
    return IdentOrType();
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 483 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_WORKERS);
    else
    return IdentOrType();
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 490 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_LOCAL);
    else
    return IdentOrType();
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 497 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_GLOBAL);
    else
    return IdentOrType();
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 504 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_TIED);
    else
    return IdentOrType();
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 511 "scanner.l"
{
    count();
    if (on_ompix_line)
    return(OMPIX_DETACHED);
    else
    return IdentOrType();
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 520 "scanner.l"
{ gobbleline(); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 521 "scanner.l"
{ gobblecomment(); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 524 "scanner.l"
{ count(); return(INT); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 525 "scanner.l"
{ count(); return(VOID); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 526 "scanner.l"
{ count(); return(RETURN); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 527 "scanner.l"
{ count(); return(PRIVATE); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 528 "scanner.l"
{ count(); return(PUBLIC);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 530 "scanner.l"
{ count(); return(BREAK);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 531 "scanner.l"
{ count(); return(CONTINUE);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 532 "scanner.l"
{ count(); return(DO);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 533 "scanner.l"
{ count(); return(ELSE); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 534 "scanner.l"
{
                         count();
                         if (on_omp_line)
                            return (OMP_FOR);
                         else
                            return(FOR);
                       }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 541 "scanner.l"
{
                         count();
                         if (on_omp_line)
                            return(OMP_STATIC);
                       }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 546 "scanner.l"
{ count();return(IF);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 547 "scanner.l"
{ count(); return(WHILE); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 548 "scanner.l"
{ count(); return(SMCOPEN); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 549 "scanner.l"
{ count(); return(SMCINPUT); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 550 "scanner.l"
{ count(); return(SMCOUTPUT); }
	YY_BREAK
/*
   * Identifiers, constants and strings
   */
case 81:
YY_RULE_SETUP
#line 555 "scanner.l"
{ count(); return(IDENTIFIER); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 556 "scanner.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 557 "scanner.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 558 "scanner.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 559 "scanner.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 561 "scanner.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 562 "scanner.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 563 "scanner.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 564 "scanner.l"
{ count(); return(STRING_LITERAL); }
	YY_BREAK
/*
   * Operators
   */
case 90:
YY_RULE_SETUP
#line 569 "scanner.l"
{ count(); return(ADD_ASSIGN); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 570 "scanner.l"
{ count(); return(SUB_ASSIGN); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 571 "scanner.l"
{ count(); return(MUL_ASSIGN); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 572 "scanner.l"
{ count(); return(DIV_ASSIGN); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 573 "scanner.l"
{ count(); return(MOD_ASSIGN); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 575 "scanner.l"
{ count(); return(INC_OP); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 576 "scanner.l"
{ count(); return(DEC_OP); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 577 "scanner.l"
{ count(); return(AND_OP); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 578 "scanner.l"
{ count(); return(OR_OP); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 579 "scanner.l"
{ count(); return(LE_OP); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 580 "scanner.l"
{ count(); return(GE_OP); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 581 "scanner.l"
{ count(); return(EQ_OP); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 582 "scanner.l"
{ count(); return(NE_OP); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 583 "scanner.l"
{ count(); return(RIGHT_OP); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 584 "scanner.l"
{ count(); return(LEFT_OP);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 585 "scanner.l"
{ count(); return('@');}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 586 "scanner.l"
{ count(); return('<'); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 587 "scanner.l"
{ count(); return('>'); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 589 "scanner.l"
{ count(); return(';'); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 590 "scanner.l"
{ count(); return('{'); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 591 "scanner.l"
{ count(); return('}'); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 592 "scanner.l"
{ count(); return(','); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 593 "scanner.l"
{ count(); return(':'); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 594 "scanner.l"
{ count(); return('='); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 595 "scanner.l"
{ count(); return('('); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 596 "scanner.l"
{ count(); return(')'); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 597 "scanner.l"
{ count(); return('['); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 598 "scanner.l"
{ count(); return(']'); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 600 "scanner.l"
{ count(); return('-'); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 601 "scanner.l"
{ count(); return('+'); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 602 "scanner.l"
{ count(); return('*'); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 603 "scanner.l"
{ count(); return('/'); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 604 "scanner.l"
{ count(); return('%'); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 605 "scanner.l"
{ count(); return('!'); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 606 "scanner.l"
{ count(); return('^'); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 607 "scanner.l"
{ count(); return('|'); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 608 "scanner.l"
{ count(); return('&'); }
	YY_BREAK
/*
   * Spaces, newlines etc.
   */
case 127:
YY_RULE_SETUP
#line 613 "scanner.l"
{ count(); }
	YY_BREAK
case 128:
/* rule 128 can match eol */
YY_RULE_SETUP
#line 614 "scanner.l"
{
                         count();
                         if (on_omp_line || on_ompix_line)
                         {
                           on_omp_line = on_ompix_line = 0;  /* Line finished */
                           return('\n');
                         }
                       }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 622 "scanner.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 623 "scanner.l"
ECHO;
	YY_BREAK
#line 2177 "scanner.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 533 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 533 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 532);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 623 "scanner.l"




/* Notice that in the following we make use of input() and unput().
 * Those destroy yytext[] but we don't care what happens to it
 * at those points in the code.
 */


int yywrap()
{
  return(1);
}


/* Called upon encountering a line starting with '#' which does not
 * contain an OpenMP pragma.
 * We actually throw this line away but before doing so we check if
 * it conveys line number information from the original file. This
 * must be of the form:
 *    # <number> "<filename>"
 */
void sharp()
{
    char c, line[SCANNER_STR_SIZES] = {0}, *s, *t;
    int  lineno = -1;
    
    for (s = line; (c = input()) != '\n' && c != 0; )   /* Read in the line */
    if (s-line < SCANNER_STR_SIZES-2)
    *s++ = c;
    
    if (c == 0) return;          /* End of file - ignore anyways */
    *s = 0;                      /* Ignore \n and force end of string */
    thisfile_line++;             /* Update counters */
    thisfile_column = 0;
    
    if ( sscanf(line, "%d", &lineno) < 0 ) return;   /* Nope -- no line number */
    
    for (s = line; *s != '\"' && *s != 0; s++)       /* Find the " */
    ;
    if (*s == 0) return;                             /* Nope -- no file name */
    
    for (t = (++s); *s != '\"' && *s != 0; s++)      /* Find the next " */
    ;
    if (t == s) return;                              /* Nope -- empty file name */
    *s = 0;
    strncpy(origfile_name, t, SCANNER_STR_SIZES-1);
    origfile_line = lineno;
    marker_line   = thisfile_line;
}


/* Update line/column counters & generate the thingy to return to the parser */
void count()
{
  int i, nonempty = 0;

  for (i = 0; yytext[i] != 0; i++)
    if (yytext[i] == '\n')
    {
      thisfile_column = 0;
      thisfile_line++;
    }
    else
      if (yytext[i] == '\t')
        thisfile_column += ( 8 - (thisfile_column % 8) );
      else
      {
        thisfile_column++;
        if (!isspace(yytext[i]))
          nonempty = 1;
      };

  if (nonempty)
    strcpy(yylval.name, yytext);
}

/* Gobble till end of line (i.e. ignore C++ // comments)
 */
void gobbleline()
{
    char c;
    for ( ; (c = input()) != '\n' && c != 0; )   /* Read in the line */
    ;
    thisfile_line++;             /* Update counters */
    thisfile_column = 0;
}


/* Gobble spaces (returns the non-space char found)
 */
char gobblespaces()
{
    char c;
    for ( ; (c = input()) != 0 && isspace(c); )
    if (c == '\n')
    {
        thisfile_line++;
        thisfile_column = 0;
    }
    else
    thisfile_column++;
    if (c)
    thisfile_column++;
    return (c);
}


/* Gobble till the end of comment (i.e. ignore C comments)
 * We actually don't need to recognize comments, since we scan a
 * file that has already been preprocessed. However, we need this
 * functionality for testing purposes.
 * The code is a bit dump, i.e. it won't handle nested comments,
 * and it won't check for strings.
 */
void gobblecomment()
{
    char c, done = 0;
    
    /* Never put the !done *after* the (c = input()) != 0. Order matters!! */
    for ( ; !done && (c = input()) != 0; )
    {
        if (c == '\n')
        {
            thisfile_line++;               /* Update counters */
            thisfile_column = 0;
            continue;
        }
        thisfile_column++;
        if (c == '*')
        {
            while ((c = input()) == '*')
            thisfile_column++;
            if (c == '\n')
            {
                thisfile_line++;             /* Update counters */
                thisfile_column = 0;
            }
            else
            {
                thisfile_column++;
                if (c == '/')
                done = 1;
            }
        }
    }
}


/* Gobble (but store) till the end of an attribute phrase ((...)).
 * The code is a bit dump, i.e. it won't handle strings with "))" in them.
 */
int sc_scan_attribute(char **string)
{
    char c, done = 0, text[SCANNER_STR_SIZES];
    int  n;
    
    c = gobblespaces();
    if (c != '(' || ((c = input()) != '(')) return (-1);
    thisfile_column++;
    text[0] = text[1] = '(';
    
    /* Never put the !done *after* the (c = input()) != 0. Order matters!! */
    for (n = 2; !done && (c = input()) != 0 && n < SCANNER_STR_SIZES; )
    {
        text[n++] = c;
        if (c == '\n')
        {
            thisfile_line++;               /* Update counters */
            thisfile_column = 0;
            continue;
        }
        thisfile_column++;
        if (c == ')')
        {
            if ((c = input()) == ')')
            done = 1;
            text[n++] = c;
            if (done)
            {
                text[n++] = 0;
                *string = strdup(text);
            }
            thisfile_column++;
        }
    }
    return ( (c == 0 || n >= SCANNER_STR_SIZES) ? -1 : 0 );
}


/* Set everything up to scan from a string */
void sc_scan_string(char *s)
{
  yy_scan_string(s);
  *origfile_name = 0;
  sc_set_filename("injected_code");
}


/* Utilities */

void sc_set_start_token(int t)
       { start_token = t; thisfile_line = 1; thisfile_column = 0;
         marker_line = origfile_line = 0; }
void sc_set_filename(char *fn)
       { strncpy(thisfile_name, fn, 255); }
char *sc_original_file()
       { return ( (*origfile_name) ?  origfile_name : thisfile_name ); }
int  sc_original_line()  { return(thisfile_line - marker_line + origfile_line);}
int  sc_line()           { return(thisfile_line); }
int  sc_column()         { return(thisfile_column); }
void sc_pause_openmp()   { on_omp_line = 0; }
void sc_start_openmp()   { on_omp_line = 1; }

