target_sources(sources PRIVATE

smc-compute/ops/shamir/BitLTC.cpp 
smc-compute/ops/shamir/LTZ.cpp 
smc-compute/ops/shamir/Mod2.cpp 
smc-compute/ops/shamir/Mod2M.cpp 
smc-compute/ops/shamir/Mod2MS.cpp 
smc-compute/ops/shamir/Mult.cpp 
smc-compute/ops/shamir/Operation.cpp 
smc-compute/ops/shamir/EQZ.cpp 
smc-compute/ops/shamir/PrefixMultiplication.cpp 
smc-compute/ops/shamir/SDiv.cpp 
smc-compute/ops/shamir/Trunc.cpp 
smc-compute/ops/shamir/BitOps.cpp 
smc-compute/ops/shamir/DotProduct.cpp 
smc-compute/ops/shamir/Pow2.cpp 
smc-compute/ops/shamir/BitDec.cpp 
smc-compute/ops/shamir/AddBitwise.cpp 
smc_compute/ops/shamir/PreOpL.cpp 
smc-compute/ops/shamir/B2U.cpp 
smc-compute/ops/shamir/PreOr.cpp 
smc-compute/ops/shamir/TruncS.cpp 
smc-compute/ops/shamir/Inv.cpp 
smc-compute/ops/shamir/TruncPr.cpp 
smc-compute/ops/shamir/FLMult.cpp 
smc-compute/ops/shamir/FLLTZ.cpp 
smc-compute/ops/shamir/FLDiv.cpp 
smc-compute/ops/shamir/FLAdd.cpp 
smc-compute/ops/shamir/FLEQZ.cpp 
smc-compute/ops/shamir/FLRound.cpp 
smc-compute/ops/shamir/PrivIndex.cpp 
smc-compute/ops/shamir/Random.cpp 
smc-compute/ops/shamir/PrviPtr.cpp 
smc-compute/ops/shamir/Int2FL.cpp 
smc-compute/ops/shamir/FL2Int.cpp 
smc-compute/ops/shamir/FPDiv.cpp 
smc-compute/ops/shamir/AppRcr.cpp 
smc-compute/ops/shamir/IntAppRcr.cpp 
smc-compute/ops/shamir/Open.cpp 
smc-compute/ops/shamir/Norm.cpp
)